### ISSUE TITLE
Exercicio

### ISSUE THREAD

**Issue by juliabraganholli** [IgorPereira98/Exercicio0903#1]

**Comment by juliabraganholli** [comment]
eae !

**Comment by IgorPereira98** [comment]
Eu com o Vinicius cuidamos do HTML/css ? :+1:

**Comment by juliabraganholli** [comment]
a gente fez o formulario aaaaaaaaaaaaa

**Comment by juliabraganholli** [comment]
eai porra qq ceis fizeram por enquanto ????

**Comment by IgorPereira98** [comment]
Fizemos o html com o formulário

**Comment by juliabraganholli** [comment]
manda

**Comment by juliabraganholli** [comment]
pra gente formatar

**Comment by juliabraganholli** [comment]
da push e me manda o link

**Comment by IgorPereira98** [comment]
Tamo tentando dar o maximo de commit possivel aqui pra não faltar depois

**Comment by IgorPereira98** [comment]
já demos push com os campos criados para formatarem

**Comment by juliabraganholli** [comment]
nois n consegue subir a porta localhost

**Comment by IgorPereira98** [comment]
digita php -S localhost:1010

**Comment by juliabraganholli** [comment]
tão fazendo o php ?

**Comment by IgorPereira98** [comment]
fizemos ja

**Comment by juliabraganholli** [comment]
a gente mandou o formulario com css ai, dá pull e junta com php

**Comment by juliabraganholli** [comment]
n esquece do commit

**Comment by IgorPereira98** [comment]
Precisa consertar o erro no PHP que não estamos conseguindo

**Comment by juliabraganholli** [comment]
manda

**Comment by juliabraganholli** [comment]
pode dar pull

**Comment by juliabraganholli** [comment]
?

**Comment by juliabraganholli** [comment]
ow, ceis conseguiram o php ?
